### ISSUE TITLE
Publication missing: Various Efforts of Enhancing Real World Online Discussions

### ISSUE THREAD

**Issue by n2o** [jelmervdl/eca2019#2]
Hi,
I sent you an email with the missing information about our publication. It would be great if you'd add these to the proceedings.
Thanks!

**Comment by n2o** [comment]
Hi, I sent you an email a few moments ago. Hope everything is now fine. Please contact me if you need further information or if we need to change anything. Thanks for your effort! 👍

**Comment by jelmervdl** [comment]
Hi @n2o I've received it and everything should be okay now! Thanks!
